PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#farm-bc91aede-bec3-4226-8fc4-2583f71e2abd> as ?farm)
   ?farm a was:Farm.    
   ?farm hmas:contains ?tractor.
   ?tractor a was:Tractor.
 }
}
