PREFIX ex: <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?section WHERE {
  GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#> {
    BIND(<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#farm-bc91aede-bec3-4226-8fc4-2583f71e2abd> AS ?farm)
    ?farm was:hasLandSection ?section.
    ?section a was:LandSection.
  }
}