PREFIX ex: <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?x1 ?y1 ?x2 ?y2 WHERE {
  GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#> {
    BIND(<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-joshua#landSection1> AS ?section)
    ?section was:hasCoordinates ?coords.
    ?coords was:hasCoordinateX1 ?x1;
            was:hasCoordinateY1 ?y1;
            was:hasCoordinateX2 ?x2;
            was:hasCoordinateY2 ?y2.
  }
}